### PR TITLE
Patch 1

### PR DESCRIPTION
**Pull request by NamanZelawat**

### CODE REVIEW

**Comment by NamanZelawat** [comment]
Session 25/1/2019 description

**Comment by sanketsingh24** [comment]
You are editing the wrong file, make a file named 'Session_1.md' in folder '2018-19' and add the content there.

**Comment by NamanZelawat** [comment]
No access of pushing and new file is created on my repository in a new branch as no permission to is granted  on the given repository to create a new file.

**Comment by NamanZelawat** [comment]
sent a pull request

**Pull request merged**
